### PR TITLE
Use Ruby 1.9+ hash literal syntax

### PR DESCRIPTION
**Pull request by dcarral**
;)

### CODE REVIEW

**Comment by randycoulman** [comment]
Thanks for the contribution, @dcarral!  I, too, prefer the 1.9 hash syntax over hash rockets.  However, the rest of the code base uses hashrockets consistently, so I think we should keep the README as-is for now.

I'll keep this PR open for a little while to give @kytrinyx a chance to weigh in.

**Comment by dcarral** [comment]
@randycoulman Thanks a lot for the instant feedback! :) It makes sense. What do you think about changing to the new syntax in the codebase too, then?

**Comment by kytrinyx** [comment]
Hi @dcarral thanks so much for taking the time to make this change.

While I don't feel particularly strongly about one syntax over another (e.g. I use tabs in Go and spaces in Ruby), I _do_ feel strongly about consistency.

With hashes, the colon syntax only applies to keys that are symbols... and only symbols that are alphanumeric. If we use the colon syntax and need other types of keys, or keys that have hyphens, then this will introduce inconsistency, which has an added cost when reading it.

For this reason I would prefer to leave the hash syntax as is.

**Comment by randycoulman** [comment]
Hi, @dcarral.  We're super open to improvements to the README.  See also #25 that has some additional ideas.

But for this particular change, we're going to keep things as-is to maintain the consistency that @kytrinyx talked about.

I'm going to close this PR, but as I said, other README improvements are most welcome.  Thanks again for taking the time!

**Pull request closed without merging**
