### PR TITLE
Make the --ask flag backwards compatible

### PR DESCRIPTION
**Pull request by kytrinyx**
No matter what order the files are in in the .approvals file, this
should work.

### CODE REVIEW

**Comment by randycoulman** [comment]
This will work for the `mv` command, but might break on the diff command above.  Should we pull the `split` and such up to the top and be explicit about both the `diff` and the `mv`?  For the `diff`, it should definitely be approved first, then received to keep the intention of the original fix.

If you're too busy, let me know, and I can make the change.

**Comment by kytrinyx** [comment]
Yeah, good point. I'll fix it now. Thanks!

**Comment by kytrinyx** [comment]
I've released 0.0.20 -- sorry about the mess!

**Comment by randycoulman** [comment]
Looks good, thanks!

**Pull request merged**
