### PR TITLE
Slightly polish README

### PR DESCRIPTION
**Pull request by dcarral**
;)

### CODE REVIEW

**Comment by randycoulman** [comment]
Hi, @dcarral.  Thanks for these changes.  The first two commits look great, and I'd like to merge them.  But the last commit (switching from single quotes to double quotes) is inconsistent with the coding style used in the rest of the project, so I think we should leave them as single quotes.

Could you please revert that one commit (466eed1)?  If you feel strongly about that change, perhaps split it off into its own PR so that we can consider it separately.

**Comment by dcarral** [comment]
@randycoulman Thanks a lot for your instant feedback :) I've unified the style with single quotes, does it look better now? ;)

**Comment by randycoulman** [comment]
Yes, it does, thanks!  Waiting for green, then I'll merge.

**Comment by kytrinyx** [comment]
Thanks so much @dcarral!

Re: quotes, I would be open to a pull request that changes the (entire) codebase to consistently use double quotes instead of a mix of single and double quotes.

**Pull request merged**
