### PR TITLE
Allow failures on ruby-head

### PR DESCRIPTION
**Pull request by kytrinyx**
This is not going to be a good solution long term.
See https://github.com/kytrinyx/approvals/pull/73#issuecomment-249385183

### CODE REVIEW

**Comment by kytrinyx** [comment]
OK, let's see if that passes :)

**Comment by randycoulman** [comment]
Responding to https://github.com/kytrinyx/approvals/pull/73#issuecomment-249385446 here, since I think this is a better place for the conversation...

I believe a gemspec file is "just Ruby", so it should be possible to put in some conditional code that requires one version of the gem or another depending on the Ruby version.  I don't have time today to work on trying that, but hopefully this gives you an idea.

**Comment by kytrinyx** [comment]
That sounds promising (and not too difficult). @shawnacscott also mentioned the Appraisals gem for running different dependencies per version: https://github.com/thoughtbot/appraisal which could make this completely trivial.

I'm about to get on an airplane, so I won't be able to try it today either.

**Comment by shawnacscott** [comment]
I don't have as much experience with whether or not Appraisals works in production, But I would think so... Maybe @reidab would be willing to offer his opinion on Appraisals and on conditional logic in Gemfiles. I know we had some issues with that on Calagator, but I don't think I could accurately summarize them.

**Comment by shawnacscott** [comment]
Refreshing myself from our issues (https://github.com/calagator/calagator/issues/97), looks like we eventually used the gemspec to specify the different dependencies per version

**Pull request merged**
