### PR TITLE
Update gemspec to make 'json' an explicit dependency

### PR DESCRIPTION
**Pull request by ThomasKoppensteiner**
This PR addresses #93.

### CODE REVIEW

**Comment by ThomasKoppensteiner** [comment]
Background:
I had some issues installing `approvals` today because `json 2.6.2` wasn't correctly released for JRuby (https://github.com/flori/json/issues/497).
During the investigation, I wondered, where the `json` dependency of `approvals` is defined.

**Review by Goltergaul — APPROVED** [review]

**Comment by ThomasKoppensteiner** [comment]
@randycoulman can you please review this pull request?
You added the `ext/mkrf_conf.rb` file with [this commit](https://github.com/kytrinyx/approvals/commit/39191779480bc424b9bac2a194f16b2296a0b47a).

**Comment by randycoulman** [comment]
@ThomasKoppensteiner Sorry, I haven't been using Ruby for several years now, so I don't have the context to properly review this any more.

**Comment by geeksam** [comment]
[Sorry, apparently I didn't have notifications configured for this repo. I should get them now.]

Given that Ruby 1.9.3 was EOL'd seven years ago, it seems reasonable to drop the `ext/mkrf_conf.rb` file.  I'm still not familiar with this codebase, but given @Goltergaul's +1, I'll merge this.  :)

Thanks!

**Comment by geeksam** [comment]
...just as soon as I get the project set up and the specs passing, that is...

**Pull request merged**
