### PR TITLE
Reverse the order of diffed files when verifying

### PR DESCRIPTION
**Pull request by randycoulman**
When diffing the received and approved files during verification, put
the `approved` file first so that the diff shows what would change if
the `received` file was approved as the new golden master.  This seems
clearer and easier to understand.

* This change will also need to be made to https://github.com/kytrinyx/approvals/pull/59

* This code would not handle filenames with embedded spaces.  However,
  the existing code also suffers from the same problems.  The `diff` and
  `mv` commands would fail with such filenames.

* A better implementation might be to change the order of the filenames
  in the `.approvals` file itself.  I'd be happy to re-submit this PR
  with that implementation instead.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yepp, this makes sense. I'll rebase this onto the new master (with all your other changes in it), but you might be right that a better solution is to change the `.approvals` file itself.

**Comment by kytrinyx** [comment]
Merged in 11b1ef1eae43d4f14b85bbafe296ded72a1618fe

**Comment by randycoulman** [comment]
I just pushed a change with the order of the files reversed right in `.approvals`.  Feel free to accept or just close the PR without merging.  Either way, the functionality works.

Thanks for looking at these so quickly!

**Comment by kytrinyx** [comment]
I'm just waiting for the build to pass, then I'll pull this in. Thanks for the improvements (and good luck with your workshop).

**Comment by randycoulman** [comment]
Thanks!

**Comment by kytrinyx** [comment]
v0.0.18 should be up on rubygems now.

**Comment by randycoulman** [comment]
Got it pulled and ready to go.  Thanks again!

**Pull request merged**
